name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: arc-runner-set
    environment: test
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          # Remove any newlines from the secret
          echo "$KUBE_CONFIG" | tr -d '\n' | base64 -d > ~/.kube/config
          
          # Verify the config file was created properly
          ls -la ~/.kube/
          echo "=== Config file content ==="
          cat ~/.kube/config
          echo "=== End config file ==="
          
          # Set proper permissions
          chmod 600 ~/.kube/config
          
          # Test basic config reading
          kubectl config view
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Verify cluster access
        run: |
          kubectl cluster-info
