name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        env:
          PREMIUM_REPO_USER: ${{ secrets.PREMIUM_REPO_USER }}
          PREMIUM_REPO_PASS: ${{ secrets.PREMIUM_REPO_PASS }}
        run: ./gradlew test

      - name: Build JAR
        env:
          PREMIUM_REPO_USER: ${{ secrets.PREMIUM_REPO_USER }}
          PREMIUM_REPO_PASS: ${{ secrets.PREMIUM_REPO_PASS }}
        run: ./gradlew -Pvaadin.productionMode=true bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: jmix/jmix-bookstore:latest

