name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: self-hosted
    environment: test
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      
      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          # Remove any newlines from the secret
          echo "$KUBE_CONFIG" | tr -d '\n' | base64 -d > ~/.kube/config
          
          # Verify the config file was created properly
          ls -la ~/.kube/
          echo "=== Config file content ==="
          cat ~/.kube/config
          echo "=== End config file ==="
          
          # Set proper permissions
          chmod 600 ~/.kube/config
          
          # Test basic config reading
          kubectl config view
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Verify cluster access
        run: |
          kubectl cluster-info
