name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: arc-runner-set  
    environment: test
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          # Remove any newlines from the secret
          echo "$KUBE_CONFIG" | tr -d '\n' | base64 -d > ~/.kube/config
          
          # Verify the config file was created properly
          ls -la ~/.kube/
          echo "=== Config file content ==="
          cat ~/.kube/config
          echo "=== End config file ==="
          
          # Set proper permissions
          chmod 600 ~/.kube/config
          
          # Test basic config reading
          kubectl config view
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Verify cluster access
        run: |
          kubectl cluster-info
      
      - name: Setup Java with manual download
        run: |
          # Create directory in workspace with proper permissions
          mkdir -p java-install
          
          # Try multiple download URLs
          JDK_URLS=(
            "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz"
            "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz"
          )
          
          for url in "${JDK_URLS[@]}"; do
            echo "Trying: $url"
            if curl -fL -o jdk.tar.gz "$url"; then
              echo "Download successful"
              # Extract to current directory (workspace)
              tar -xzf jdk.tar.gz
              # Find the extracted directory
              JDK_DIR=$(find . -name "jdk-21*" -type d | head -1)
              echo "JDK found in: $JDK_DIR"
              # Add to PATH
              echo "$GITHUB_WORKSPACE/$JDK_DIR/bin" >> $GITHUB_PATH
              break
            else
              echo "Download failed, trying next URL..."
            fi
          done
          
          # Verify installation
          echo "Current PATH: $PATH"
          $GITHUB_WORKSPACE/$JDK_DIR/bin/java -version
            
      - name: Build JAR
        env:
          PREMIUM_REPO_USER: ${{ secrets.PREMIUM_REPO_USER }}
          PREMIUM_REPO_PASS: ${{ secrets.PREMIUM_REPO_PASS }}
        run: ./gradlew -Dorg.gradle.jvmargs='-Xms8g -Xmx24g' -Pvaadin.productionMode=true build -x test

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Container Image
        run: |
          ./gradlew jib -Djib.to.image=ghcr.io/${{ github.repository }}:latest -Djib.from.image=eclipse-temurin:21-jre
